### ISSUE TITLE
Not working with Django 3.1

### ISSUE THREAD

**Issue by Veilkrand** [jazzband/django-cities-light#243]
The current 3.6.0 version uses `django-autoslug-iplweb` which is incompatible with the latest Django 3.1
It trows:
```
"... site-packages/autoslug/utils.py", line 15, in <module>
    from django.db.models.fields import FieldDoesNotExist, DateField
ImportError: cannot import name 'FieldDoesNotExist' from 'django.db.models.
```

Following https://docs.djangoproject.com/en/dev/releases/3.1/ `The compatibility import of django.core.exceptions.FieldDoesNotExist in django.db.models.fields is removed.`
It need to change `from django.db.models.fields import FieldDoesNotExist` with`from django.core.exceptions import FieldDoesNotExist`

**Comment by marianoeramirez** [comment]
Hi @Veilkrand This error is already solved on the máster branch. Please test and let us now.

We are having problems deploying the lastest version to PyPI.

**Comment by Veilkrand** [comment]
@marianoeramirez I installed the dev version 3.8 locally and it works correctly. But I need the PyPI binary for the remote environments. Thanks

**Comment by AndyClifton** [comment]
@Veilkrand you can include the most recent release from GitHub in your requirements.txt file using something like this:

```
django-allauth>=0.42.0    # via -r requirements.in
django-autoslug>=1.9.8    # via django-cities-light
git+https://github.com/jazzband/django-cities-light.git@3.8.0#egg=django-cities-light  # via -r requirements.in
django-crispy-forms>=1.9.2  # via -r requirements.in
django-extensions>=3.0.9  # via -r requirements.in
````

(the others are just for illustration). This stops it from looking for the 3.8.0 release from PyPI.

**Comment by NaturalBornCamper** [comment]
Any approximate date as to when 3.8 will be on PyPI?

**Comment by marianoeramirez** [comment]
The version 3.8.0 is released on pypi. https://pypi.org/project/django-cities-light/3.8.0/
